### ISSUE TITLE
Roadmap for GUI

### ISSUE THREAD

**Issue by SumanthRH** [r2mishra/roebling#3]
- [x] Start with [`asciichart`](https://github.com/madnight/asciichart/) and integrate with `brick`
- [x] Write a progress bar widget that gets updated in real time
- [x] Write up the structs for other widgets in Ali - Parameters, Latencies, Bytes, Status Codes, Errors, Others (which do we choose?)
- [x] Update `asciichart` plot to get updated in real-time
- [x] Combine different widgets into one interface

**Comment by SumanthRH** [comment]
More tasks:

- [ ] Add support to read in from channels
- [ ] Add unit tests
- [ ] Combine progress bar with updated asciichart
